#! /usr/bin/python3

import pygame

pygame.init()

# Définir la taille de la fenêtre
screen = pygame.display.set_mode((900, 600), pygame.SCALED + pygame.RESIZABLE)

# Définir le titre de la fenêtre
pygame.display.set_caption("BACK FLIP SIMULATOR 2023")

display = pygame.Surface((300, 200))

# Boucle principale du jeu
running = True
while running:
    # Gérer les événements
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
    
    # Mettre à jour l'affichage
    pygame.display.update()

# Quitter Pygame
pygame.quit()
